### ISSUE TITLE
Toast.makeText(mContext, "缺少访问地理位置的权限", Toast.LENGTH_SHORT).show();

### ISSUE THREAD

**Issue by star-heng** [aifeier/AndroidGpsDemo#1]
GPS定位和网络定位 都 报这个问题
是在  GPSLocation中的 startListener() 中d的  Toast
在 联想K50-t5  Android6.0 和  vivoY33  ANdroid 5.0 测试

**Comment by aifeier** [comment]
已添加权限请求
